name: story-lifecycle
description: "Full multi-agent story lifecycle: SM+PM prioritize → BA+PM+UX define requirements → Architect design → Dev build (feature branch) → QA test → DevOps deploy to Railway → Tech Writer document + Create PR → Code Reviewer review + resolve PR comments + merge"
author: "SideDecked"

config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/story-lifecycle"
instructions: "{installed_path}/instructions.xml"
template: false

variables:
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"
  agent_path: "{project-root}/_bmad/bmm/agents"

input_file_patterns:
  epics:
    description: "Epic files for story prioritization"
    whole: "{planning_artifacts}/epic-*.md"
    load_strategy: "FULL_LOAD"
  sprint_status_file:
    description: "Current sprint status and story states"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"
  architecture:
    description: "Architecture docs for technical design phase"
    whole: "docs/architecture/*.md"
    load_strategy: "FULL_LOAD"
