name: story-lifecycle
description: "Full multi-agent story lifecycle: SM+PM prioritize → BA+PM+UX requirements → UX Designer wireframe + party mode review + advanced elicitation (UI stories) → Architect design + plan file → Dev TDD → QA → DevOps deploy → Tech Writer docs → Two-stage code review → PR merge"
author: "SideDecked"

config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/story-lifecycle"
instructions: "{installed_path}/instructions.xml"
template: false

variables:
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"
  agent_path: "{project-root}/_bmad/bmm/agents"
  plan_dir: "{project-root}/docs/plans"
  ux_wireframe_dir: "{planning_artifacts}"

# Superpowers skill references (for documentation — invoked at runtime)
superpowers:
  tdd: "superpowers:test-driven-development"
  verification: "superpowers:verification-before-completion"
  debugging: "superpowers:systematic-debugging"
  requesting_review: "superpowers:requesting-code-review"
  receiving_review: "superpowers:receiving-code-review"
  executing_plans: "superpowers:executing-plans"
  finishing_branch: "superpowers:finishing-a-development-branch"

input_file_patterns:
  epics:
    description: "Epic files for story prioritization"
    whole: "{planning_artifacts}/epic-*.md"
    load_strategy: "FULL_LOAD"
  sprint_status_file:
    description: "Current sprint status and story states"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"
  architecture:
    description: "Architecture docs for technical design phase"
    whole: "docs/architecture/*.md"
    load_strategy: "FULL_LOAD"
  ux_design_spec:
    description: "UX design specification for wireframe alignment"
    whole: "_bmad-output/planning-artifacts/ux-design-specification.md"
    load_strategy: "FULL_LOAD"

# Session boundaries (guidance for orchestrator)
sessions:
  discovery:
    phases: [1, 2, "2B", 3]
    description: "Select story, define requirements, produce UX wireframe (UI stories), produce implementation plan"
    artifacts_saved:
      - "docs/plans/{date}-{story-key}-plan.md"
      - "_bmad-output/planning-artifacts/ux-{story-key}-wireframe.html (UI stories only)"
  build:
    phases: [4, 5]
    description: "Implement story with TDD, validate with integration tests"
    artifacts_saved: ["feature branch with all code committed"]
  ship:
    phases: [6, 7, 8]
    description: "Deploy to production (conditional), document, review, merge"
    artifacts_saved: ["merged PRs on main", "production deployment"]
