name: story-docs
description: "Update and create project documentation for a completed story. Reads all impacted docs, updates existing docs (CHANGELOG, architecture, READMEs, story file, sprint-status), creates new docs (API reference, architecture, user guides) when warranted, and validates against documentation-standards.md."
author: "SideDecked"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/story-docs"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"
template: false

variables:
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"
  doc_standards: "{project-root}/_bmad/_memory/tech-writer-sidecar/documentation-standards.md"
  architecture_docs: "docs/architecture"

input_file_patterns:
  architecture:
    description: "Architecture docs that may need updating"
    whole: "docs/architecture/*.md"
    load_strategy: "FULL_LOAD"
  standards:
    description: "Documentation quality standards"
    whole: "{project-root}/_bmad/_memory/tech-writer-sidecar/documentation-standards.md"
    load_strategy: "FULL_LOAD"
